### ISSUE TITLE
https://github.com/ThunderCore-Developer/Jumpstart-Program/issues/1#issue-798816929

### ISSUE THREAD

**Issue by HE1-SIM** [ThunderCore-Developer/Jumpstart-Program#33] opened 2021-02-26 08:51 UTC
https://github.com/ThunderCore-Developer/Jumpstart-Program/issues/1#issue-798816929

_Originally posted by @HE1-SIM in https://github.com/ThunderCore-Developer/Jumpstart-Program/issues/1#issuecomment-786503501_

**Comment by batuka1220** [comment] 2021-02-26 08:58
comment

**Comment by batuka1220** [comment] 2021-02-26 08:58
nice tt

**Comment by batuka1220** [comment] 2021-02-26 08:59
nice nicw

**Comment by batuka1220** [comment] 2021-02-26 08:59
Duplicate of #

**Closed** 2021-03-02 05:24 UTC
